### ISSUE TITLE
Privacy concern: images outside project are visible 

### ISSUE THREAD

**Issue by EwoudSmit** [DIAGNijmegen/rse-gcapi#106]
* Grand Challenge API Client version:
* Python version: 
* Operating System: 

### Description

With the gcapi, you are able to download images of other projects including metadata (e.g. patient name).
This seems a potential privacy issue. 
I would expect only to be able to access the images of my own reader study/database.

### What I Did

client = gcapi.Client(token=token)
images_list = list(client.images.iterate_all()) # Gives many images outside my project
for image in image_list:
    patient_name = image["patient_name"]

Maybe require:
images_list = list(client.images.iterate_all(params={"slug": slug})) 
with the slug linked to the token?

**Comment by jmsmkn** [comment]
You can only download images that you have access to. You have access to other images as they are part of public algorithm results - there are currently 160 images are visible to all users, out of the ~250,000 in the database.

A reminder that security issues should not be posted in a public forum such as this, but an email should be sent to security@grand-challenge.org where issues can be fixed before responsible disclosure.
