### ISSUE TITLE
Feature request: Upload of docker algorithm images through gcapi

### ISSUE THREAD

**Issue by silvandeleemput** [DIAGNijmegen/rse-gcapi#146]
* Grand Challenge API Client version: 0.11.0

### The issue

Currently, I am having trouble letting GC automatically build some of the algorithms from the Dockerfiles in the repositories that I have linked to my algorithms. I like that when I tag my algorithms while iterating on them that they get built and automatically get deployed to GC. However, I encounter various issues regarding the builds:

* The GC docker image builds don't have BUILDKIT enabled, causing the algorithm container image build to fail. This might be simple to add, but could be undesirable because of security concerns.

* Some of my algorithms have cross-repository dependencies from private repositories (these are primarily DIAGNijmegen, but cause the build to fail). This might be hard to address, I don't want to make the required repositories public and I can't pass on secrets to the GC build process.

* Some Dockerfiles depend on the images in the private docker image repository of DIAGNijmegen, which cannot be pulled from on GC. Could be fixed by moving some of the images to a public repository.

### Feature request

I think while some of the independent issues can be solved, it might be a better solution to also allow uploading algorithm container images through gcapi. This would allow algorithm maintainers to build the containers themselves and upload the resulting artifacts using a CI setup. 

I would like to discuss if this is desirable/feasible. If it is, I can probably spend some time realizing this feature.

**Comment by jmsmkn** [comment]
This would require exposing Algorithm Image REST API endpoints. We want to change those soon and adding them now would make that more difficult, so let's not do this right now. Buildkit can be enabled if absolutely necessary. Not interested in adding support for private Docker repositories.
