### ISSUE TITLE
When using chunks during upload, the complete-multipart-upload call will fail with an Internal server error

### ISSUE THREAD

**Issue by perrykipkerrie** [DIAGNijmegen/rse-gcapi#148]
* Grand Challenge API Client version: 1.0.0
* Python version: 3.11
* Operating System: Win 11 22H2

### Description
When setting the chunk size to a lower settings (e.g. 100.000) a server error is thrown when callling the complete-multipart-upload call. 

### What I Did expected to happen.
Merging of the uploads to a single file.

### What I Did

Setting the chunksize to e.g. 100 * 1024 and then calling:

`token = 'secret'
client = gcapi.Client(token=token)

algorithm_1 = client.algorithms.detail(slug="stratified-transformer-instseg")

registration_job = client.run_external_job(
    algorithm="stratified-transformer-instseg",
    inputs={
        "3d-teeth-scan": [Path("C:/Users/robin/Desktop/bun.obj")],
    }
)`
```

```

**Comment by jmsmkn** [comment]
Your proposed upload is smaller than the minimum allowed object size. Each part must be at least 5 MB in size, except the last part.

**Comment by perrykipkerrie** [comment]
Thank you for your quick response. This seems reasonable. Do you know if this was stated somewhere in the GC docs?

**Comment by jmsmkn** [comment]
No, it is not something that should be modified by the overwhelming majority of users of grand challenge so is not documented, don't change it.

**Comment by perrykipkerrie** [comment]
Thank you for your explanation, it's solved.
