### ISSUE TITLE
Merge several reused definitions into one file

### ISSUE THREAD

**Issue by HarmvZ** [DIAGNijmegen/rse-gcapi#20]
I noticed several duplicate definitions in the JSON schemas, for example `uuid`, `api-link`, `gc-db-object`, `line-object`, etc. I think this can be refactored by moving the duplicates to a separate `definitions.json` file and reference them in the schemas using: 
`{ "$ref": "definitions.json#/name" }`
Is there a reason this is not used currently @jmsmkn / @pkcakeout?
If not, I can do this while I'm creating a JSON schema for `LandmarkAnnotationSet` objects since I also need to reuse several of those definitions.

**Comment by jmsmkn** [comment]
cc @silvandeleemput @miriam-groeneveld 

We've all had problems with this, at the moment they're replicated in 3 places, gcapi, cirrus core and grand challenge. Probably evalutils in the near future too. We need to work out a better approach as this is terrible. 

Can you be specific with what you're proposing? How would it work for these other libraries? Be aware that the definitions are subtly different.

**Comment by HarmvZ** [comment]
The original schemas are only in this repo and replicated in the other places as git submodules, right? If not, then that's a different problem which I'm not sure how to solve. What I meant was to just remove the duplicate definitions in the JSON schemas in this repository.

My proposal is to create a `definitions.json` file containing all reusable object definitions. For example:
```
{
    "$schema": "http://json-schema.org/draft-07/schema#",

    "definitions": {
        "uuid": {
            "type": "string",
            "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
        },
        "api-link": {
            "type": "string",
            "pattern": "^https?://.*[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/$"
        },
        "gc-db-object": {
            "type": "object",
            "properties": {
                "pk": {
                    "$ref": "#/definitions/uuid"
                },
                "api_url": {
                    "$ref": "#/definitions/api-link"
                }
            },
            "required": ["pk", "api_url"]
        }
}
```

And in a file where we need to use `gc-db-object` we can reference the `definitions.json` file. For example: 

```
{
    "$schema": "http://json-schema.org/draft-07/schema#",

    "allOf": [
        { "$ref": "definitions.json#definitions/gc-db-object" },
        {
            "type": "object",
            "properties": {
                ...other properties...
             }
        }
    ]
}
```

As explained here: https://json-schema.org/understanding-json-schema/structuring.html#reuse


If the definitions are (subtly) different this approach cannot be used.

**Comment by pkcakeout** [comment]
I posted a word of caution on PR #21. Also one more thing: The "proper" way to prevent duplication of these schemas all over the shop is to expose them on some public HTTP server and then use a FQN domain name to refer to them. We could do this with github-pages if we want. Then we can refer to them from anywhere with a unique identifier and anybody who wants verification against our schemas can do so. We can even locally cache those in our containers and use them from there. If I remember correctly, jsonschema was quite flexible with its resolvers.

**Comment by jmsmkn** [comment]
Closing this as there is an existing issue for it on grand challenge https://github.com/comic/grand-challenge.org/issues/1017
