### ISSUE TITLE
gcapi does not install jsonschemas via setup.py

### ISSUE THREAD

**Issue by pkcakeout** [DIAGNijmegen/rse-gcapi#23]
* Grand Challenge API Client version: master
* Python version: 3.6
* Operating System: all

### Description

When attemtping to create a binary distribution or attempting to install gcapi directly from github via `pip install https://github.com/DIAGNijmegen/rse-gcapi/archive/master.zip`, the jsonschema are not installed and importing gcapi succeedingly fails. `setup.py` should be modified to also install the jsonschemas.

**Comment by jmsmkn** [comment]
Please give the PR a try, it was a blind fix.

**Comment by pkcakeout** [comment]
Oh wow thanks! That helps a lot! The pip install rules are driving me crazy - mainly because they first failed on Windows and now also on Linux. I will give it a try!
