### ISSUE TITLE
Extend JSON schema to support datetime?

### ISSUE THREAD

**Issue by HarmvZ** [DIAGNijmegen/rse-gcapi#26]
In #24 I added support to the `Draft7Validator` for `datetime` strings. This will allow JSON schemas to contain objects like this:
`{ "type": "datetime" }`

This allows validation of the `datetime` strings serialized by Django Rest Framework for fields that contain dates, such as the `created` field. One issue then is that by adding the extra type in our schemas, they are not complying with the default JSON schema standard. Is this a good idea? Or does anyone have a suggestion of a better way of doing this?

**Comment by jmsmkn** [comment]
cc: @pkcakeout

**Comment by HarmvZ** [comment]
Discussed this with Paul and realized that there is a better way to do this. There is support for `format` checking in JSON shemas as shown [here](https://python-jsonschema.readthedocs.io/en/stable/validate/#validating-formats). I implemented this new way of datetime checking in https://github.com/DIAGNijmegen/rse-gcapi/pull/24/commits/00122e5a12e2419204efe0079c48957e6020a12d.
