### ISSUE TITLE
Use latest_ready_image instead of algorithm_container_images in _get_latest_algorithm_image

### ISSUE THREAD

**Issue by haimasree** [DIAGNijmegen/rse-gcapi#38]

**Comment by haimasree** [comment]
@jmsmkn 
Using latest_ready_image will make it impossible to test test_run_external_algorithm as it will error out before the job is submitted. What kind of fix do you want? 
I can think of updating init_gc_demo with a valid container

**Comment by jmsmkn** [comment]
Use monkey patching to fake this response https://docs.pytest.org/en/3.0.1/monkeypatch.html
